version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/certs:/etc/nginx/certs:ro
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-network

  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-letsencrypt
    restart: unless-stopped
    environment:
      - DEFAULT_EMAIL=teu-email@exemplo.com
    volumes:
      - /etc/nginx/certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - nginx-proxy
    networks:
      - proxy-network

  vue:
    build: .
    container_name: vue-app
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=amecctech.com,www.amecctech.com
      - LETSENCRYPT_HOST=amecctech.com,www.amecctech.com
      - LETSENCRYPT_EMAIL=hhmocumbi@gmail.com
    expose:
      - "80"
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
