version: '3'
services:
  vue:
    build: .
    environment:
      - VIRTUAL_HOST=amecctech.techsolutionslda.com
      - VIRTUAL_PORT=80
    networks:
      - proxy-network
    restart: unless-stopped
networks:
  proxy-network:
    external: true
