version: '3.8'

services:
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-letsencrypt
    restart: unless-stopped
    environment:
      - DEFAULT_EMAIL=teu-email@seudominio.com
    volumes:
      - /etc/nginx/certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-network
    depends_on:
      - vue

  vue:
    build: .
    container_name: amecctech-vue
    restart: unless-stopped
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=amecctech.com,www.amecctech.com
      - LETSENCRYPT_HOST=amecctech.com,www.amecctech.com
      - LETSENCRYPT_EMAIL=teu-hhmocumbi@gmail.com
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
